-- MySQL Script generated by MySQL Workbench
-- Mon Jul 22 08:21:52 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fleetcontrol
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fleetcontrol` ;

-- -----------------------------------------------------
-- Schema fleetcontrol
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fleetcontrol` ;
SHOW WARNINGS;
USE `fleetcontrol` ;

-- -----------------------------------------------------
-- Table `fleetcontrol`.`tblclientcompany`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fleetcontrol`.`tblclientcompany` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fleetcontrol`.`tblclientcompany` (
  `idClient` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID number assigned by system as PRIMARY KEY',
  `txtCompanyName` VARCHAR(50) NOT NULL COMMENT 'Name of the client company.',
  `intPrimaryContact` INT(11) NOT NULL COMMENT 'Name of the primary individual dealt with',
  `dDateBegan` DATE NOT NULL COMMENT 'Date began doing business with',
  `dDateEnd` DATE NOT NULL COMMENT 'Date business with ended',
  `txtCompanyAddress1` VARCHAR(255) NOT NULL COMMENT 'Mailing Address of Company',
  `txtCompanyAddress2` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Mailing Address of Company (Optional)',
  `txtCity` VARCHAR(50) NOT NULL COMMENT 'City in which Company resides\n',
  `intState` INT(11) NOT NULL COMMENT 'State in which Company resides.  Lookup.',
  `txtZipCode` VARCHAR(10) NOT NULL COMMENT 'Postal code in which Company resides',
  `txtCountry` VARCHAR(50) NULL DEFAULT 'USA' COMMENT 'Country in which Company resides\n',
  `txtClientPhone` VARCHAR(14) NOT NULL COMMENT 'Phone number of Client Company\n',
  `txtFaxNumber` VARCHAR(14) NULL DEFAULT NULL COMMENT 'Fax Number of Client Company',
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1
COMMENT = ' 2.1. tblClientCompanyInfo\nPurpose of entity: Maintains information on business entities that will use FleetControl. \nStandard abbreviation: tblClientCompany.\nNumber of entities: Unlimited.\nApplication that “creates” this entity: Fleet Control, ClientCompanyInfo.aspx.\nApplications that modify or feed this entity: Fleet Control, ClientCompanyInfo.aspx.\nApplications that read attributes of this entity: Fleet Control, ClientCompanyInfo.aspx.\nPrimary key attribute for this entity: idClient. \nOther keys / indexes of this entity: intPrimaryContact, intState.';

SHOW WARNINGS;
CREATE UNIQUE INDEX `idClient_UNIQUE` ON `fleetcontrol`.`tblclientcompany` (`idClient` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fleetcontrol`.`tblmileage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fleetcontrol`.`tblmileage` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fleetcontrol`.`tblmileage` (
  `idMileage` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID number assigned by system as PRIMARY KEY\n',
  `txtVehicle` VARCHAR(17) NOT NULL COMMENT 'Foreign Key providing Lookup for vehicle',
  `dServiceDate` DATETIME NOT NULL COMMENT 'Date and time of vehicle service.',
  `intServiceCenter` INT(11) NOT NULL COMMENT 'Foreign Key providing Lookup for Service Center providing service',
  `intBeginOdometer` INT(11) NOT NULL COMMENT 'Mileage of vehicle at last service date.',
  `intEndOdometer` INT(11) NOT NULL COMMENT 'Mileage of vehicle at current service date.',
  `curCost` DECIMAL(10,0) NOT NULL COMMENT 'Cost in dollars of current purchase.',
  `intGallons` INT(11) NOT NULL COMMENT 'Number of Gallons of fuel purchased',
  PRIMARY KEY (`idMileage`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1
COMMENT = ' 2.2. tblMileage\nPurpose of entity: Keeps track of the mileage and miles per gallon for each vehicle. \nStandard abbreviation: tblMileage.\nNumber of entities: Unlimited.\nApplication that “creates” this entity: Fleet Control.\nApplications that modify or feed this entity: Fleet Control.\nApplications that read attributes of this entity: Fleet Control.\nPrimary key attribute for this entity: idMileage. \nOther keys / indexes of this entity: intVehicle, intServiceCenter';

SHOW WARNINGS;
CREATE UNIQUE INDEX `idMileage_UNIQUE` ON `fleetcontrol`.`tblmileage` (`idMileage` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `intServiceCenter_idx` ON `fleetcontrol`.`tblmileage` (`intServiceCenter` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fleetcontrol`.`tblservicerepairs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fleetcontrol`.`tblservicerepairs` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fleetcontrol`.`tblservicerepairs` (
  `idServiceRepairs` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID number assigned by system as PRIMARY KEY',
  `intVehicle` INT(11) NOT NULL COMMENT 'Foreign Key providing Lookup for vehicle',
  `dServiceDate` DATETIME NOT NULL COMMENT 'Date and time of service or repair',
  `intServiceCenter` INT(11) NOT NULL COMMENT 'Foreign Key providing Lookup of Service Center',
  `intOdometer` INT(11) NULL DEFAULT NULL COMMENT 'Mileage at time of Service or Repair',
  `curCost` DECIMAL(10,0) NULL DEFAULT NULL COMMENT 'Cost of Service or Repair',
  `intServiceRepairType` INT(11) NOT NULL COMMENT 'Foreign Key providing Lookup for type of Service or Repair',
  `txtNotes` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idServiceRepairs`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1
COMMENT = ' 2.4. tblServiceRepairs\nPurpose of entity: Maintain records of service and repairs to vehicles in the fleet. \nStandard abbreviation: tblServiceRepairs.\nNumber of entities: Unlimited.\nApplication that “creates” this entity: Fleet Control.\nApplications that modify or feed this entity: Fleet Control.\nApplications that read attributes of this entity: Fleet Control.\nPrimary key attribute for this entity: idServiceRepairs. \nOther keys / indexes of this entity: intVehicle, intServiceCenter, intServiceRepairType.';

SHOW WARNINGS;
CREATE UNIQUE INDEX `idServiceRepairs_UNIQUE` ON `fleetcontrol`.`tblservicerepairs` (`idServiceRepairs` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fleetcontrol`.`tblservicerepairtype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fleetcontrol`.`tblservicerepairtype` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fleetcontrol`.`tblservicerepairtype` (
  `idServiceRepairType` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID number assigned by system as PRIMARY KEY\n',
  `txtServiceRepair` VARCHAR(50) NOT NULL COMMENT 'Service or Repair performed',
  `txtNotes` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Notes pertaining to Service or repair performed',
  PRIMARY KEY (`idServiceRepairType`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1
COMMENT = ' 2.5. tblServiceRepairType\nPurpose of entity: Maintain records of the types of service and repairs made to vehicles in the fleet. \nStandard abbreviation: tblServiceRepairType.\nNumber of entities: Unlimited.\nApplication that “creates” this entity: Fleet Control.\nApplications that modify or feed this entity: Fleet Control.\nApplications that read attributes of this entity: Fleet Control.\nPrimary key attribute for this entity: idServiceRepairType. \nOther keys / indexes of this entity: none.';

SHOW WARNINGS;
CREATE UNIQUE INDEX `idServiceRepairType_UNIQUE` ON `fleetcontrol`.`tblservicerepairtype` (`idServiceRepairType` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fleetcontrol`.`tblserviceschedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fleetcontrol`.`tblserviceschedule` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fleetcontrol`.`tblserviceschedule` (
  `idServiceSchedule` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idServiceSchedule`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idServiceSchedule_UNIQUE` ON `fleetcontrol`.`tblserviceschedule` (`idServiceSchedule` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fleetcontrol`.`tblsignin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fleetcontrol`.`tblsignin` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fleetcontrol`.`tblsignin` (
  `idSignin` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID number assigned by system as PRIMARY KEY\n',
  `txtUserName` VARCHAR(50) NOT NULL COMMENT 'Username for Fleetcontrol.',
  `txtUserPassword` VARCHAR(50) NOT NULL COMMENT 'User password for Fleetcontrol.',
  `intUser` INT(11) NOT NULL COMMENT 'Foreign Key providing Lookup for User',
  PRIMARY KEY (`idSignin`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1
COMMENT = ' 2.7. tblSignin\nPurpose of entity: Maintains records of who can log into FleetControl. \nStandard abbreviation: tblSignin.\nNumber of entities: Unlimited.\nApplication that “creates” this entity: Fleet Control.\nApplications that modify or feed this entity: Fleet Control.\nApplications that read attributes of this entity: Fleet Control.\nPrimary key attribute for this entity: idSignin. \nOther keys / indexes of this entity: intUser. ';

SHOW WARNINGS;
CREATE UNIQUE INDEX `idSignin_UNIQUE` ON `fleetcontrol`.`tblsignin` (`idSignin` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fleetcontrol`.`tblstate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fleetcontrol`.`tblstate` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fleetcontrol`.`tblstate` (
  `idState` INT(11) NOT NULL AUTO_INCREMENT,
  `txtStateName` VARCHAR(45) NOT NULL,
  `txtStateAbbreviation` VARCHAR(10) NULL DEFAULT NULL,
  `txtStateCode` CHAR(2) NOT NULL,
  PRIMARY KEY (`idState`))
ENGINE = InnoDB
AUTO_INCREMENT = 61
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fleetcontrol`.`tbluser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fleetcontrol`.`tbluser` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fleetcontrol`.`tbluser` (
  `idUser` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID number assigned by system as PRIMARY KEY\n',
  `intClientCompany` INT(11) NOT NULL COMMENT 'Foreign Key providing Lookup for Client Company',
  `intServiceCenter` INT(11) NOT NULL COMMENT 'Foreign Key providing Lookup for Service Center',
  `txtFirstName` VARCHAR(50) NOT NULL COMMENT 'First Name of Individual',
  `txtMiddleName` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Middle Name of Invidual.  Optional',
  `txtLastName` VARCHAR(45) NOT NULL COMMENT 'Last Name of Individual',
  `txtPhone` VARCHAR(14) NOT NULL COMMENT 'Phone number individual can be reached at',
  `txtEmail` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Email address of individual\n',
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1
COMMENT = ' 2.9. tblUser\nPurpose of entity: Maintains records for individuals maintained in FleetControl. \nStandard abbreviation: tblUser.\nNumber of entities: Unlimited.\nApplication that “creates” this entity: Fleet Control.\nApplications that modify or feed this entity: Fleet Control.\nApplications that read attributes of this entity: Fleet Control.\nPrimary key attribute for this entity: idUser. \nOther keys / indexes of this entity: intClientCompany, intServiceCenter. ';

SHOW WARNINGS;
CREATE UNIQUE INDEX `idUser_UNIQUE` ON `fleetcontrol`.`tbluser` (`idUser` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fleetcontrol`.`tblvehicle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fleetcontrol`.`tblvehicle` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fleetcontrol`.`tblvehicle` (
  `idVehicle` VARCHAR(17) NOT NULL COMMENT 'Vehicle Identification Number\n',
  `intClientCompany` INT(11) NOT NULL COMMENT 'Foreign Key providing Lookup for Client Company',
  `yrVehicleYear` YEAR(4) NOT NULL COMMENT 'Year of vehicle',
  `txtVehicleMake` VARCHAR(50) NOT NULL COMMENT 'Make of vehicle',
  `txtVehicleModel` VARCHAR(50) NOT NULL COMMENT 'Model of Vehicle',
  `txtVehicleIdentifier` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Unit Name',
  `txtLicenceNumber` VARCHAR(10) NULL DEFAULT NULL COMMENT 'Licence Number',
  `txtColor` VARCHAR(15) NULL DEFAULT NULL COMMENT 'Color of Vehicle',
  `intOdometer` INT(11) NULL DEFAULT NULL COMMENT 'Original odometer reading at purchase of vehicle',
  `txtKeyIgnition` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Ignition Key Number',
  `txtKeyDoor` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Door Key number',
  `dtPurchaseDate` DATE NULL DEFAULT NULL COMMENT 'Date of Vehicle Purchase',
  `curPurchasePrice` DECIMAL(10,0) NULL DEFAULT NULL COMMENT 'Original Purchase price of vehicle',
  `intDealership` INT(11) NULL DEFAULT NULL COMMENT 'Foreign Key - idServiceCenters - Lookup',
  `txtNotes` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Notes',
  PRIMARY KEY (`idVehicle`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = ' 2.10. tblVehicle\nPurpose of entity: Maintain information pertaining to the vehicles maintained in the fleet. \nStandard abbreviation: tblVehicle.\nNumber of entities: Unlimited.\nApplication that “creates” this entity: Fleet Control.\nApplications that modify or feed this entity: Fleet Control.\nApplications that read attributes of this entity: Fleet Control.\nPrimary key attribute for this entity: idVehicles. \nOther keys / indexes of this entity: intClientCompany, intDealerState. ';

SHOW WARNINGS;
CREATE INDEX `intClientCompany_idx` ON `fleetcontrol`.`tblvehicle` (`intClientCompany` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `intDealership_idx` ON `fleetcontrol`.`tblvehicle` (`intDealership` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
